local configs = require('nvim-treesitter.configs')
configs.setup({
  ensure_installed = {
    'arduino',
    'bash',
    'c',
    'c_sharp',
    'cmake',
    'comment',
    'cpp',
    'css',
    'diff',
    'dockerfile',
    'git_config',
    'git_rebase',
    'gitattributes',
    'gitcommit',
    'gitignore',
    'java',
    'javascript',
    'jsdoc',
    'json',
    'json5',
    'jsonc',
    'kotlin',
    'latex',
    'lua',
    'make',
    'markdown',
    'markdown_inline',
    'passwd',
    'python',
    'rust',
    'scheme',
    'sql',
    'ssh_config',
    'tsx',
    'typescript',
    'udev',
    'vim',
    'vimdoc',
    'yaml',
  },
  sync_install = false,
  auto_install = true,
  highlight = { enable = true },
  indent = { enable = true },
})
